services:
  nextjs:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./.nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.nginx/rc.conf:/etc/rc
    depends_on:
      - nextjs
